on: [push, pull_request]

jobs:
  job1:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.12]
        include:
          - os: ubuntu-latest
            python-version: 3.12

        exclude:
          - os: ubuntu-latest
            python-version: 3.11
          - os: windows-latest
            python-version: 3.12
          - os: macos-latest
            python-version: 3.11
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          mkdir -p testresult
          pytest --junitxml=testresult/results.xml
          echo "This is a test output" > testresult/output.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: testresult/

      - name: Build Project
        run: |
          mkdir -p build
          echo "This is a build output for Python ${{matrix.python-version}} on ${{matrix.os}}" > build/output.txt
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  download:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download test reuslt artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: download-test-results/
            
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: download-build-artifacts/

      - name: Display the downloaded test result
        run: cat download-test-results/results.xml

      - name: Display the downloaded build artifacts
        run: cat download-build-artifacts/output.txt
